# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Thetearofmoon"
repo_name: "cv-arxiv-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 50

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Motion Generation": 
        filters: ["Motion Generation", "Human Motion Generation"]
    "Motion Synthesis": 
        filters: ["Motion Synthesis", "Human Motion Synthesis"]
    "HOI":
        filters: ["HOI", "Human Object Interactions", "Human-Object Interactions", "Human-Object Interaction", "Human Object Interaction"]
    "LOMC":
        filters: ["overcome the limitations of motion capture datasets", "motion capture datasets", "3D motion capture is arduous", "small scale motion capture data"]
    "UL":
        filters: ["Unsupervised Learning", "Unsupervised learning algorithm"]
    "IS":
        filters: ["Image Synthesis", "image generation"]
